---

galaxy_info:
  role_name: base
  author: Aotokitsuruya
  description: Base Role for Rails
  license: Apache-2.0
  min_ansible_version: 2.9.0
  github_branch: master
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - centos
dependencies: []
